default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: worldpz
  password: worldpz
  pool: 5

development:
  <<: *default
  database: worldpz

# test:
#   <<: *default
#   database: worldpz_test

production:
  <<: *default
  database: worldpz_production
  username: worldpz
  password: <%= ENV['WORLDPZ_DATABASE_PASSWORD'] %>
